### ISSUE TITLE
Czarnolistowanie tagow nie dziala

### ISSUE THREAD

**Issue by endrjux** [wykopx/WykopX#1]
Niestety, z jakiegos powodu czarnolistowanie tagow nie dziala. Używam stylu prawie od jego poczatku i nigdy nie dzialalo.

![image](https://user-images.githubusercontent.com/688476/216403553-f283de90-f5df-4132-8531-ad305b04b374.png)

W inspektorze ten wpis wyglada tak:

![image](https://user-images.githubusercontent.com/688476/216405693-435456d0-b60a-40ff-89e6-ab1d9dbcbd56.png)

A Twój styl (w zakładce "Style Editor") wyglada tak:

![image](https://user-images.githubusercontent.com/688476/216407530-6d8561e0-525e-414a-99bd-3e25d4d0c38d.png)

Lata całe juz nie mialem za bardzo do czynienia z CSS, ale na pierwszy rzut oka wydaje mi sie, ze wszystko sie zgadza, wiec zupelnie nie rozumiem dlaczego to nie dziala. Nie wiem czy to ma jakies znaczenie, ale konta nie mam i zalogowany nie jestem.

Sprawdzalem czy wylaczenie wszystkich rozszerzen (poza Stylusem) cos zmienia, ale niestety nie.

Firefox 107, Linux.

**Comment by wykopx** [comment]
Po pierwsze hej, nie myślałem, że ktokolwiek tutaj zgłosi jakies błędy :)  
Dlatego przepraszam, że odpisuję tak późno.

Po drugie, nie sądziłem, że osoby bez konta na wykopie będą instalowały ten dodatek - nawet mi to do głowy nie wpadło :)  muszę sprawdzić co się rozjeżdza u niezalogowanego użytkownika. Dzięki! 

I dzięki za raport błędu. Ale skoro nie masz konta na wykopie to faktycznie, tutaj zgłosiłeś. Świetnie :)


Blacklistowanie jak najbardziej działa... 

![image](https://user-images.githubusercontent.com/123825950/216745689-5c5aedde-afdc-4dc1-b9e4-86665d18fd72.png)

Niestety nie działa na Firefoxie, a pytasz o powód. 

Ten powód jest bardzo prosty: **od 15 lat użytkownicy Firefoxa proszą Mozillę o obsługę selektora **:has****, ale Mozilla nadal nie zaimplementowała w silniku Gecko jego obsługi - a na nim opiera się czarnolistowanie i w sumie bardzo dużo innych elementów Wykop X (więc one też niestety nie będą działać).

https://bugzilla.mozilla.org/show_bug.cgi?id=418039
![image](https://user-images.githubusercontent.com/123825950/216745786-df1725b9-72e6-4bc4-82c0-41cf0a02d78f.png)

![image](https://user-images.githubusercontent.com/123825950/216745729-02bb4c76-353c-4844-8f46-868148add4d1.png)

Poradziłbym Tobie (i innym uzytkownikom Firefoxa), żeby odblokować `layout.css.has-selector.enabled`

![image](https://user-images.githubusercontent.com/123825950/216744767-f8eb32ec-a5a2-48a9-aa26-3e76dae9a2ab.png)

Ale i tak prawdopodobnie nie zadziała ponieważ z tego co czytam - po prostu nie działa i tyle. 
Wszystkie przeglądarki poza Firefoxem już od jakiegoś czasu obsługują 
![image](https://user-images.githubusercontent.com/123825950/216745634-c870b110-3813-4e41-9521-f4d3deee09f3.png)

![image](https://user-images.githubusercontent.com/123825950/216745379-fc2ecc75-6047-423a-bcdd-07c27a3351b4.png)   


Ale głowa do góry, po 15 latach jest szansa, że w tym roku w końcu to zrobią. 

![image](https://user-images.githubusercontent.com/123825950/216745808-6b91f5ae-553f-40ca-862d-74e0b7db08da.png)

Natomiast zgłoszony przez W3C do wdrożenia do CSS został w 2018 roku i od tamtego czasu wszystkie inne przeglądarki już zaimplementowały go do (głównie dzięki WebKit i Blink w Chrome) 
https://www.w3.org/TR/2018/WD-selectors-4-20180201/#has-pseudo


Tak więc niestety muszę zamknąć to zgłoszenie, bo nie ode mnie zależy kiedy Mozilla zaimplementuje w końcu w swoim silniku obsługę jednego z najważniejszych i najbardziej użytecznych (moim zdaniem) selektorów w CSS.

W sumie to nie myślałem, że ktoś jeszcze używa Firefoxa w dzisiejszych czasach. :) 

Pozdrawiam i czekam na więcej zgłoszeń - nie tylko błędów ale też propozycji nowych funkcji.

**Comment by endrjux** [comment]
Dzieki wielkie za wszystkie szczegoly! Oczywiscie, na to ze FF nie umie w CSS nic nie poradzisz. :-)

Poprobuje zgodnie z tym co napisales a jak nie, to poczekam az zaimplementuja.

Dziekuje za pomoc!

**Comment by wykopx** [comment]
@endrjux wiem, że to nie jest rozwiązanie problemu, ale sugeruję Ci zrobić tak
Ściągnij wersję portable jakiejś nowoczesnej przeglądarki np. Chrome albo Opery
Zainstaluj tylko stylusa i tampermonkey
Otwórz wykop i wybierz z menu Chrome'a "Zainstaluj jako aplikację"

https://github.com/wykopx/WykopX/wiki/%E2%96%AA%F0%9F%93%B1-wykop.pl-jako-aplikacja-PWA
Nie musisz używać Chroma przecież do niczego więcej, a wykop w trybie aplikacji PWA działa spoko i w zasadzie nawet nie odczujesz tego, że to nie jest Firefox.

**Comment by lukaszpolowczyk** [comment]
@endrjux Wykop X korzysta z eksperymentalnych nowości w CSS, nie wiadomo po co.
A błędy są najwyżej w Stylusie albo preprocesorze do stylusa.

Nie rozumiem decyzji autora Wykop X, żeby używać eksperymentalnych technologii i olewać część użytkowników.

To namawianie do zmiany przeglądarki internetowej to po prostu xD.

**Comment by wykopx** [comment]
> Wykop X korzysta z eksperymentalnych nowości w CSS, **NIE WIADOMO PO CO**.

No faktycznie, nie wiadomo po co. 

> Nie rozumiem decyzji autora Wykop X, żeby **używać eksperymentalnych technologii** i olewać część(*1) użytkowników.

Temat dotyczy niedziałającego czarnolistowania w Firefoxie. 

Napisz mi proszę - nie używając selektora **:has()** kod CSS, 
który - przykładowo - wyłączy wyświetlanie na mikroblogu **wpisów, które nie mają w treści #taga**  

Ja napisałem coś takiego, ale bez "eksperymentalnej technologii"  selektora **:has()** który wspierają wszystkie(*2) 
przeglądarki oprócz Firefoxa - po prostu nie umiem.

Łukasz Połowczyk, Ty na pewno jesteś ode mnie dużo lepszy w tym, jesteś bardzo dobrym programistą, z tego co widziałem na Twoim GitHubie i masz bardzo dużą wiedzę i sporo umiesz w programowaniu, a wiem, że na pewno nie jesteś hejterem internetowym, więc pomóż i pokaż mi jak to zrobić.  Bo ja nie umiem inaczej.

Firefox obsługuje eksperymentalną technologię selectora :not() więc może tym się można posłużyć?

Mój kod, który nie działa w Firefoxie:

``` css
/* BLACKLIST ENTRIES WITHOUT TAGS ON MICRO STREAM */
section.stream.microblog > div.content > section.entry:not(.own):not(.reply):not(:has(div.wrapper button)):not(:has(> article > div.edit-wrapper > div.content > section.entry-content > div.wrapper > a[href^={"\/tag\/"}])) {
      display: none;
}
```

Bardzo Cię proszę, pokaż mi jak w CSS osiągnąć czarnolistowanie bez selektora **:has()** 
Jestem naprawdę bardzo ciekaw jak to zrobić, żeby te rzeczy działały też w FF. Proszę Cię o pomoc.


***  
   
   
   
Ten CSS to w ogóle głupi wymysł. Kiedyś to wystarczył HTML i było lepiej, a nie to co dzisiaj...
``` html
  <center bgcolor="#ccdddd">
    <font face="serif" color="#ff0000" size="5">
         HTML jest najlepszy
    </font>
  </center>
```



Ja rozumiem, że poczułeś się bardzo urażony tym, że wspomniałem, że **Twoja ulubiona przeglądarka** - którą uważasz za **najlepszą na świecie** i której używasz od wielu, wielu lat i napisałeś do niej wiele rozszerzeń - nie umie obsługiwać pewnych elementów, z którymi pozostałe przeglądarki sobie radzą, ale ja osobiście głęboko wierzę, że już niedługo Firefox nadgoni i będzie lepiej wypadał w testach:

![image](https://user-images.githubusercontent.com/123825950/218354424-45edfbce-ee98-488d-b38a-11bdbe8ec3e8.png)
  
   
***   
   
   
   
   
* 1 - czyli połowę z 3% osób, które korzystają z różnych wersji Firefoxa
* 2 - wszystkie przeglądarki oprócz Firefoxa   

![image](https://user-images.githubusercontent.com/123825950/218352795-4d3c9be8-1c40-45f2-8fb5-6c0edd9da97c.png)

**Comment by lukaszpolowczyk** [comment]
> Ja napisałem coś takiego, ale bez "eksperymentalnej technologii" selektora :has() który wspierają wszystkie(*2)
> przeglądarki oprócz Firefoxa - po prostu nie umiem.

JSem. Po prostu nie ma po co się upierać na CSS.

**Comment by endrjux** [comment]
Panowie, nie ma sie co awanturowac. Oczywiscie nie zamierzam zmieniac przegladarki z powodu wypoka, Chromium zle dziala na linuksie i nie bede sie z nim bawic dla strony ze smiesznymi obrazkami. Uzywalem Chromium wiele lat i kierunek zmian mi sie nie podoba. FF nie jest idealne, ale przynajmniej bardziej robi to co ja chce a nie to co chce firma google. ;-)

Jestem umiarkowanie cierpliwy. Widze, ze bug w stylusie jest naprawiony tylko nikt nie wie kiedy bedzie release. (Nie chce mi sie instalowac nightly :-p) Do `has` jest `layout.css.has-selector.enabled` i ok. [Sprawdzilem losowym testem z google i dziala](https://codepen.io/bramus/pen/poWJXGY) (FF 107), chociaz [na SO](https://stackoverflow.com/questions/73936048/how-do-you-enable-has-selector-on-firefox) pisza, ze okolo wersji 109 znow nie dziala.

**Comment by wykopx** [comment]
> Wykop X korzysta z eksperymentalnych nowości w CSS, nie wiadomo po co.
@endrjux @lukaszpolowczyk 

Firefox zaimplementował obsługę :has() 😁  więc Wykop X Style od teraz działa w końcu także na najnowszej wersji Firefoxa 121

https://github.com/wykopx/WykopX/wiki/%F0%9F%9A%AB-Problemy:-Mozilla-Firefox
https://github.com/wykopx/WykopX/wiki/Changelog#2450-firefox-121
