### ISSUE TITLE
proponowane tagi - wyświetlane względem popularności

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#100]
przy pisaniu posta na wstążce tagi powiny wyświetlać się od najpopularniejszego od góry :)

**Comment by dracar1** [comment]
zdaje mi się że oficjalnie jest ta opcja u każdego - a u mnie nie działa -
chcę stworzyć wpis np. #heheszki  -> wpisuję np. #hehe pojawia się wstążka
z tagami OK.

Ale u mnie widnieje to tak:

[image: image.png]


więc mogę się domyślać tylko po liczbie obserwujących jaki to tag
a poza tym tagi nie układają się od najpopularniejszych tylko właśnie
odwrotnie ;-;

chyba że jest taka opcja w stylusie i ja coś kliknąłem...

czw., 6 kwi 2023 o 15:16 Wykop X ***@***.***> napisał(a):

**Comment by wykopx** [comment]
> oficjalnie jest ta opcja u każdego
Co to znaczy, że oficjalnie opcja jest u każdego? Co to zdanie znaczy?

> wpisuję np. #hehe pojawia się wstążka z tagami OK.

Co to znaczy "pojawia się wstązka z tagami OK"?

> Ale u mnie widnieje to tak:  [image: image.png]

Nie odpisuj z e-maila, tylko wejdź na GitHuba i wklej zdjęcie.

> chyba że jest taka opcja w stylusie i ja coś kliknąłem...

Nie mam pojęcia o czym mówisz. To co napisałes nie ma żadnego sensu, używasz słów, które nijak nie da się zrozumiec, jakieś wstążki, posty, etc.  Nie wiem o co chodzi, nie chcesz napisać tego po polsku jak człowiek, więc nie będę się domyślał o czym mówisz. 

Zawsze w kazdym projekcie opis błędu czy propozycji nowej funkcjonalności powinien być jasny, czytelny i dokładny, taki, żeby od razu wiadomo było o co chodzi. To co napisałes takie nie jest.

**Comment by dracar1** [comment]
jak to wygląda u mnie:

https://streamable.com/84nrwy

-nie pojawiają się nazwy tagów [na wykopie bez wtyczki się pojawiają na liście proponowanych tagów- "wstążce"]
-najpopularniejsze tagi na liście proponowanych tagów są na dole listy

**Comment by wykopx** [comment]
Po dwóch miesiącach wykop wprowadził wyświetlanie liczby osób obserwujących tag w podpowiadanych tagach, zmieniając przy tym kod wyświetlany w okienku podpowiedzi tagów - stąd błąd. 

Błąd nie powoduje styl Wykop X tylko Wykop XS - jak go wyłączysz, problem zniknie.

Funkcja pobierania liczby obserwujących poprzez API napisana przez [xXdeepfriedXx](https://wykop.pl/ludzie/xXdeepfriedXx)
jest więc do wyrzucenia ze skryptu Wykop XS.
