### ISSUE TITLE
obserowane tagi stale przypięte po prawej stronie

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#103]
jeśli scrolluje w dół chciałbym, aby moje obserowane tagi były cały czas widoczne  -> przypięte po prawej stronie,
myślę że taka opcja była by bardzo pomocna, nie trzeba by wracać do góry

**Comment by wykopx** [comment]
Kilka razy już robiłem do tego podejście, na razie nie mam pomysłu jak to zrobić.
