### ISSUE TITLE
wklejanie adresu URL powoduje zwężenie się prawego sidebar-u

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#104]
ożna prosić o naprawę, wcześniej przy wrzucaniu dżych adresów URL link układał się w kilku linijkach[i sięgał do czerwonej linii], teraz pojawia się w 1 linijce co powoduje zwężenie się prawego sidebara (╯︵╰,)

![image](https://user-images.githubusercontent.com/127026337/228918177-74fc782d-7308-4956-bbfc-3749f461c93a.png)

**Comment by wykopx** [comment]
Podaj mi jakiś adres URL obrazka, który u Ciebie powoduje ten efekt, bo jak ja dodaję 

https://wykop.pl/cdn/c3201142/13a6b98778c154d5dc33da4e5f477164f97632a4e9fb83a302fbb96ae2ddd5f0.jpg?author=sildenafil&auth=f573f69a8a626a61b82f4b72a6835202

To wykop pozostawia i tak tylko tę część do "?" i nie mogę powtórzyć tego co masz na screenie.

**Comment by dracar1** [comment]
jak wygląda moja strona:
[image: image.png]

jak wygląda strona po wklejeniu Twojego linku

[image: image.png]


wykop x 2,11,13
wykop xs [pobrałem + dałem żeby aktualizowało codziennie itp.]

[image: image.png]

[image: image.png]

pt., 31 mar 2023 o 11:29 Wykop X ***@***.***> napisał(a):

**Comment by wykopx** [comment]
Nie mogę powtórzyć tego błędu, opis jest niejasny.

![image](https://user-images.githubusercontent.com/123825950/230376706-66dfb3a3-2f70-4d72-8223-9a16cfddcaff.png)


![image](https://user-images.githubusercontent.com/123825950/230376620-4edbb19f-90c0-49db-8bc7-8af0144e5f81.png)

**Comment by dracar1** [comment]
[zakładam że widać te zdjęcia :D ]

wklejony link -OK
![image](https://user-images.githubusercontent.com/127026337/230445794-ae9ebc55-2b82-49d1-b756-80fc90aadc37.png)

po kliknięciu "DODAJ" wygląd strony prezentuje się tak - cała strona się "dostosowuje" do sługości URL -> prawy sidebar się zwęża 

![image](https://user-images.githubusercontent.com/127026337/230446305-a68be1f0-4a48-4ccb-b490-ca88c00a6779.png)

**Comment by dracar1** [comment]
odpisałem na stronie

https://github.com/wykopx/WykopX/issues/104

wklejony adres URL we wpisie powoduje poszerzenie się "okna do wpisu" a
zwężenie prawego sidebaru

czw., 6 kwi 2023 o 14:19 Wykop X ***@***.***> napisał(a):

**Comment by dracar1** [comment]
https://streamable.com/t7j2yi

nagranie jak to wygląda z mojej perspektywy ;_;

**Comment by wykopx** [comment]
Rozumiem aczkolwiek ja nie jestem w stanie wygenerować tego błędu.
Podaj kroki, które umożliwą mi zreprodukowanie takiego zachowania.

Podaj jaką masz rozdzielczość ekranu i przy jakich włączonych opcjach takie zachowanie występuje (bo na pewno nie przy domyślnych).

Jeśli chcesz możesz wykorzystać tę wersję, żeby sprawdzić włączenie której opcji powoduje takie zachowanie.

https://userstyles.world/style/8419/wykop-x-blank

**Comment by dracar1** [comment]
pożeglowałem us siebie w ustawieniach i teraz działa - zamykam sry za kłopot

czw., 6 kwi 2023 o 19:55 Wykop X ***@***.***> napisał(a):
