### ISSUE TITLE
przywrócić przycisk "powrót na górę" po prawej stronie

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#106]
-przycisk jest w obecnej wersji vikop.ru, ALE pokazuje się u góry strony;
-proponuję pierwotne miejsce i kształt przycisku [moja luźna sugestia jak powinien wyglądać]
![przycisk_powrót_na_górę](https://user-images.githubusercontent.com/127026337/229859411-99a0a12b-5740-4a87-be94-c4ef750f8cde.png)

**Comment by wykopx** [comment]
Duplikat #92

**Comment by wykopx** [comment]
> przycisk jest w obecnej wersji vikop.ru, ALE pokazuje się u góry strony;

Gdzie niby jest ten przycisk? Pokaż mi na screenie. @dracar1

**Comment by wykopx** [comment]
> przycisk jest w obecnej wersji vikop.ru, ALE pokazuje się u góry strony;

@dracar1  to co z tym przyciskiem? Gdzie on jest na wykopie?

**Comment by dracar1** [comment]
sry białkov najwyraźniej się go pozbył[nic takiego teraz nie widzę na
tagach], u góry tagu pojawiał się prostokąt z tytułem "pojawiły się nowe
wpisy" teraz tego nie ma. myślałem żeby takowy prostokąt przesunąć na prawy
dół strony żeby służył jako powrót na górę i odświeżenie strony w jednym

czw., 6 kwi 2023 o 15:22 Wykop X ***@***.***> napisał(a):

**Comment by wykopx** [comment]
Jest cały czas, ale można go od niedawna wyłączyć
![image](https://user-images.githubusercontent.com/123825950/232352182-09dafa79-7f6b-49dc-9eb3-f2a8b9614eaf.png)

Pomysł, żeby przenieść go do prawego dolnego rogu jest dosyć ciekawy.
