### ISSUE TITLE
mikroblog i ukryte zdjecia z powiadomień

### ISSUE THREAD

**Issue by houk001** [wykopx/WykopX#107]
po wejściu w powiadomienie na części zdjęć taki widok 

Brak podglądu i ucięta górna tabelka. 

![image](https://user-images.githubusercontent.com/18401686/230374665-c1986312-9bd3-4e4e-9367-32150fc26b39.png)

Po wyłączeniu wykopx w stylus jest wyświetlane poprawnie.

https://wykop.pl/wpis/70948517/56-0-taylorswift-ladnapani

a np to działa bez problemów 
https://wykop.pl/wpis/70948175/ketchup-w-lodowce-nsfw-ladnapani-ladnadziewczyna-c

**Comment by wykopx** [comment]
U mnie działa normalnie.

![image](https://user-images.githubusercontent.com/123825950/230376057-c2e25a07-7154-4125-930f-d8e7bd00fe8a.png)

**Comment by houk001** [comment]
Chłopie z takim podejściem to wiesz co, a potem się dziwisz ze nie chce mi się zgłaszać problemów tutaj i wole na wykop napisać. Inne zgłoszenie leży 2 tygodnie i jest bug i zlewasz. 
Wstawiłem screena czego nie rozumiesz? Klikam w listę z powiadomień z tagu i otwiera sie jak widać na screenie bez zdjęcia. Czego nie rozumiesz?

**Comment by houk001** [comment]
![image](https://user-images.githubusercontent.com/18401686/230379467-65e2f723-ce20-4069-8927-7c4029f91359.png)
Kolejne takie samo zachowanie, przeglarka Brave po wyłączeniu wszystkich dodatków poza stylus i tampermonkey jest to samo

**Comment by houk001** [comment]
a o ucietą górną belkę chodzi mi o to 
ramka nad napisem otwórz w nowej karcie jest ucięta
![image](https://user-images.githubusercontent.com/18401686/230380691-b70aeb83-ab05-4df7-8eaa-3dbdb3e718f7.png)

**Comment by wykopx** [comment]
Naprawione Wykop X 2.11.16
https://github.com/wykopx/WykopX/wiki/Changelog#21116

**Comment by wykopx** [comment]
@houk001 możesz sprawdzić czy wyświetla Ci się obrazek w tym wpisie z WYŁACZONYM WykopX?

https://wykop.pl/wpis/70986731/musialem-sie-chwile-zastanowic-co-przedstawia-ten-

u mnie wygląda tak, ale potrzebuję potwierdzenia:

![image](https://user-images.githubusercontent.com/123825950/231097401-100e7ea6-67b6-4f30-9d36-8da5c7184d15.png)

**Comment by houk001** [comment]
U mnie tak
![image](https://user-images.githubusercontent.com/18401686/231098096-28cfd099-d994-4273-8336-ab6c18780a03.png)
