### ISSUE TITLE
✅ URL wykop.pl/@user-name przekierowujący na wykop.pl/ludzie/user-name

### ISSUE THREAD

**Issue by wykopx** [wykopx/WykopX#11]
URL wykop.pl/@user-name przekierowujący na wykop.pl/ludzie/user-name
Bo jest to modne, jest tak na Twitterze, fediversum, od niedawna nawet na YouTube.
I faktycznie tak jest wygodniej wpisać, jak chcesz się dostać na czyjś profil bez linka.

https://github.com/Wykop-pl/Issues/issues/45

**Comment by wykopx** [comment]
https://github.com/wykopx/WykopX/wiki/Changelog#270

**Przekierowania adresów URL**  

  
- `wykop.pl/@uzytkownik`  
Otwiera profil użytkownika (styl Twitterowy)  
Działa także z dodatkowymi parametrami, przykładowo:   
--  `wykop.pl/@uzytkownik/znaleziska`    
--  `wykop.pl/@uzytkownik/obserwowane/tagi`   
--  `wykop.pl/@uzytkownik/wpisy/plusowane`    

- `wykop.pl/#nazwatagu`   
Przenosi na podany po ukośniku tag    

- `wykop.pl/@uzytkownik/#nazwatagu`   albo     
- `wykop.pl/#nazwatagu/@uzytkownik`   
  
Wyszukuje wszystkie znaleziska i wpisy konkretnej osoby w danym tagu.  

- `wykop.pl/mikroblog/#dodaj`
Otwiera mikroblog z od razu aktywowanym polem edytora do pisania nowego wpisu na Mirko  

![przekierowaniauzytkownikow2](https://user-images.githubusercontent.com/123825950/218269741-f6b13582-8f30-440f-8061-ec0fce1fae9b.gif)

Sugestia od @look997 na https://github.com/Wykop-pl/Issues/issues/45

**Comment by look997** [comment]
@wykopx Ale wykop.pl/tag/nazwatagu/autor/uzytkownik też działa?
Bo tak było w starym wykopie, to by było przywrócenie kompatybilności.
