### ISSUE TITLE
Podmiana obrazka z belką na obrazek bez belki

### ISSUE THREAD

**Issue by ireun** [wykopx/WykopX#110]
Hej, tytuł mówi myślę wszystko, chodzi o białą belkę na dole obrazka z logiem wypoku i nazwą autora.

**Comment by wykopx** [comment]
Ta funkcja jest już od stycznia w Wykop X.

https://github.com/wykopx/WykopX/wiki/Changelog#250
![image](https://user-images.githubusercontent.com/123825950/232351832-b3d563a2-86ea-4f93-a302-f1954fcac24d.png)

**Comment by ireun** [comment]
@wykopx no właśnie nie, ta funkcja ukrywa belkę pod przyciskiem, gdybyś skopiował obrazek i go wkleił do painta to belka dalej tam jest.

**Comment by ireun** [comment]
![image](https://user-images.githubusercontent.com/695818/232498989-12749859-abf4-4c4d-97d9-78c8c3d2f51a.png)
No to u mnie coś nie działa chyba..

**Comment by wykopx** [comment]
No ale co Ty mi chcesz udowodnić, że nie wiem jak działa kod, który sam napisałem? Nie rozumiem o co Ci chodzi.

Proszę, przycisk dostał 100% przezroczystość. Nic pod nim nie ma. Belka nie jest ukryta pod przyciskiem. 

![image](https://user-images.githubusercontent.com/123825950/232501344-2e379c72-0c2b-47a1-876f-21e4915d6143.png)

**Comment by wykopx** [comment]
A co do
> gdybyś skopiował obrazek i go wkleił do painta to belka dalej tam jest.

Wystarczy skorzystać z jednego z dwóch przycisków - jeden zapisuje obrazek na dysku, drugi otwiera go w nowej karcie.
Zarówno jeden jak i drugi dotyczą obrazka BEZ belki, więc to już jest przypierdzielanie się na siłę, serio...
