### ISSUE TITLE
"Na której jestem stronie"

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#112]
Na obecnym wykopie, gdy przejdzie się np. na nr 3 stronę strony głównej to nigdzie nie pisze, że jest to 2 strona... może fajnie byłoby na samym dole dać taką informację, na której stronie się jest? (o ile to technicznie możliwe)

Mogłoby to wyglądać np. tak:
![211221](https://user-images.githubusercontent.com/125213230/233789714-587f0b8e-0d2c-4454-9ba5-e37fc89be3f2.png)

**Comment by wykopx** [comment]
Ależ opcja wyświetlania na której jesteś stronie jest dostępna na Wykopie na stronie głównej i na kolejnych podstronach.

![image](https://user-images.githubusercontent.com/123825950/233867434-f5df5fb9-7840-48a2-b208-4ca78a73b9aa.png)
![image](https://user-images.githubusercontent.com/123825950/233867446-1eaae266-012f-4458-8501-e3010f89dbc8.png)


Niestety - tylko dla niezalogowanych użytkowników.

Dla zalogowanych struktura strony się zmienia tak samo jak adres URL i na ten moment nie da się rozpoznać na której jesteśmy stronie.. kod wykopu nie udostępnia takiej informacji.
![image](https://user-images.githubusercontent.com/123825950/233867771-c76ca2eb-d48e-4fd4-831b-1881039fb2db.png)

A po przejściu na poprawny link działający dla niezalogowanego użytkownika, jeśli jesteśmy zalogowani przenosi na stronę główną:

https://wykop.pl/strona/3

Niestety nie mogę tego zrobić, bo się nie da.
