### ISSUE TITLE
Dostałeś bloka na wykopie?

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#113]
Założysz nowe konto? Będą aktualizacje jeszcze jakieś?

**Comment by wykopx** [comment]
Tak. Jest to napisane w moim profilu, prawda?

Zgodnie z regulaminem nie można zakładać nowych kont na Wykopie.

Oczywiście, że będą.

**Comment by SPSPSP10000** [comment]
Jest napisane w profilu. Wg mnie możesz założyć nowe konto, wiele osób po banie tak robi, szczególnie takim "stałym" banie. Nie można korzystać jedynie z więcej niż jednego konta na 1 IP... ale może coś się zmieniło z czasem i masz rację... no nie wiem... ja pewnie bym założył nowe konto i nie psocił, może nikt by się nie przyczepił ;)

**Comment by wykopx** [comment]
Ban jest na dwa tygodnie czyli do 18 maja, a i tak nie przeszkadza mi w niczym jeśli chodzi o pracę nad Wykop X :)

**Comment by SPSPSP10000** [comment]
A na 2 tygodnie... no to lux... łobuzie :P
