### ISSUE TITLE
Zrezygnuj ze stylus, przejdź w całości na Skrypt Użytkownika

### ISSUE THREAD

**Issue by lukaszpolowczyk** [wykopx/WykopX#12]
Ustawienia zrobić w GM_config:

https://github.com/sizzlemctwizzle/GM_config

https://github.com/sizzlemctwizzle/GM_config/wiki

https://openuserjs.org/libs/sizzle/GM_config

https://github.com/sizzlemctwizzle/GM_config/wiki/Event-Callbacks

Bo Stylus i Firefox ESR i Firefox Nightly wywala błąd 

```
Stylusowi nie udało się sparsować usercss:

too much recursion
```

...już przy 298 linijce, jeszcze w dziale `/* ==UserStyle== ... ==/UserStyle== */`, w `➖➖ ＺＮＡＬＥＺＩＳＫＡ ➖➖`.

Ewentualnie musi być znacznie mniej ustawień w stylu w Stylus (nie wykraczając poza taką liczbę linijek), bo inaczej jest błąd.

W Skrypcie Użytkownika na pewno nie będzie tego błędu.

Być może warto zgłosić ten błąd na repo Stylusa, może da się to naprawić dla Firefoksa?

W Chrome działa bez problemu.

**Comment by wykopx** [comment]
Ale to nie jest wina ani Stylusa, ani Wykop X - oba działają bez zarzutów na wszystkich przeglądarkach poza Firefoxem.
Wina jest całkowicie po stronie Firefoxa, który czasem sobie radzi, a czasem nie.

Tak jak sam napisałeś:
> W Chrome działa bez problemu.
W każdej innej przeglądarce działa bez problemu. Skoro nawet Kiwi Browser potrafi to odpalić na Androidzie...

Zresztą na Firefoxie i tak 30% funkcji Wykop X nie będzie działać ponieważ używa CSS-owego selektora :has() 
którego od 15 lat Firefox nie chce zaimplementować w swoim silniku.   

Na Firefoxie jest sporo innych mankamentów związanych ze Stylusem i one były od zawsze:
https://github.com/openstyles/stylus/wiki/FAQ#why-doesnt-my-favorite-style-work-in-firefox-57

![image](https://user-images.githubusercontent.com/123825950/218328737-facd64d7-f38c-4d31-b2da-8c10838bdd03.png)

![image](https://user-images.githubusercontent.com/123825950/218328750-623147e1-47c6-4795-bc3a-834dfba9a9c8.png)

Tak więc przerobienie stylu na userscript albo całkowicie jako osobne, instalowalne rozszerzenie i tak na niewiele się zda - Firefox po prostu tego nie ogarnie ze względu na ograniczenia silnika.

Jest mi naprawdę przykro, że niektórym osobom na Firefoxie styl nie chce działać (niektórym na Firefoxie działa, w tym u mnie)
Nie jestem w stanie tego naprawić. Męczyłem to przez kilka dni i nie znalazłem rozwiązania problemu. 

![image](https://user-images.githubusercontent.com/123825950/218328969-ae1e90a2-ef93-4af3-8438-dcfe03624717.png)


Polecam użycie jednej z przeglądarek, która obsługuje nowoczesne techniki webowe.

Bardziej się rozpisałem w tej kwestii tutaj:
https://github.com/wykopx/WykopX/issues/1#issuecomment-1416649451

**Comment by lukaszpolowczyk** [comment]
@wykopx Olewanie Firefoksa to bardzo zły pomysł.
Nie wydaje mi się żeby nowości CSSa były niezbędne do tego typu stylu użytkownika, więc jest to jakby przerost formy nad treścią i jest to marny pretekst na olanie wsparcia dla Firefoksa.

**Comment by wykopx** [comment]
Ale ja nie olewam Firefoxa. To Firefox olewa swoich użytkowników i niestety na to ja nie mam żadnego wpływu.

> Nie wiem jakie to te 30% funkcji, ale ja korzystałbym może nawet z nie 5% funkcji w ogóle. :D
No właśnie chodzi o to, że :has() jest kluczowy i używam go praktycznie wszędzie.

Napisałem w kodzie :has() 191 razy 
![image](https://user-images.githubusercontent.com/123825950/218329803-abb90486-63e7-4e97-8727-d4be4c1a3576.png)

+ jeszcze na ten moment 6 razy w skrypcie JS:
![image](https://user-images.githubusercontent.com/123825950/218329949-979fb4dc-e219-43c5-93b4-084552f11a30.png)

Więc plus minus 15-200 rzeczy w Firefoxie nie działa przez sam fakt niezaimplementowania od 15 lat selektora :has()

Zastąpienie Stylusa Stylishem, przepisanie na userscript niczego nie zmieni - silnik Firefoxa po prostu tego nie obsługuje i pod tym względem Firefox jest mocno do tyłu. 

Co jest w tym sztywnego? :)
Że nie mam wpływu na rozwój jednej z najpopularniejszych przeglądarek na świecie, której używa w polsce 11% internautów? 

> Ograniczać się do jakiejś niedopracowanej technologii bez wsparcia, jaką jest ten preprocesor i Stylus to błąd.

Widzisz ja tak nie uważam. Bo powtarzam, to nie jest wina ani preprocesora, ani Stylusa jako rozsrzerzenia.


PS. U mnie działa. 

![image](https://user-images.githubusercontent.com/123825950/218330143-03d56796-85ef-4c7b-8447-8d58f20e068a.png)

**Comment by wykopx** [comment]
Ale możesz napisać i do Firefoxa o prośbę naprawy tego błędu, i możesz napisać do autorów Stylusa - może ktoś coś wymyśli.
Byłoby świetnie

Rozszerzenie Stylus:
https://github.com/openstyles/stylus/issues
Preprocesor Stylus:
https://github.com/stylus/stylus/issues

**Comment by lukaszpolowczyk** [comment]
> Więc plus minus 150-200 rzeczy w Firefoxie nie działa przez sam fakt niezaimplementowania od 15 lat selektora :has()

Przecież to jest rzecz dodana niedawno, do Safari ze wsparcia Igalii, bo każdy myślał że tego nie da się dodać ze względu na wydajność, a potem Chrome też dodał, Firefox jest w trakcie prac nad tym (śledzę buga na Bugzilli).
Korzystasz z jakiejś zupełnie nówki funkcji, i mówisz że to niezbędne i niezaimplementowane od 15 lat. :DD

Dawniej takie coś się załatwiało skryptem przelatującym po elementach i też działało. od bardzo niedawna (kilka miesięcy?) jest dostępny `:has` na części przeglądarek...

> Co jest w tym sztywnego? :)

Ja zakładam, że jak coś nie jest wspierane to od razu to uwzględniam i robię tak, żeby jednak działało.
A Firefoksa warto wspierać nawet dla idei otwartej sieci.
No już namawianie na zmianę przeglądarki, to już naprawdę. :DD

> Widzisz ja tak nie uważam. Bo powtarzam, to nie jest wina ani preprocesora, ani Stylusa jako rozsrzerzenia.

Zakładam że jest, bo dochodzi do zapętlenia na jakimś etapie. A problem tkwi w bardzo długim etapie z `@var` na początku pliku. Dochodzi tam do jakiejś nadmiernej dziwnej pętli zrobionej na rekurencji. Ale może Firefox jakoś nadmiernie działa i coś źle interpretuje. To już trzeba by zbadać.

Jest skrajnie złe, że ja nie mogę skorzystać z garstki funkcji, które mnie interesują, bo styl ma masę niepotrzebnych mi funkcji, które i tak bym wyłączył, ale żeby je wyłączyć trzeba skorzystać z niedopracowanej technologii bez wsparcia, czyli jakiegoś preprocesora do Stylusa. :D
To jest taki absurd, że aż się za głowę łapię. xD

**Comment by lukaszpolowczyk** [comment]
https://github.com/stylus/stylus/issues/2755

**Comment by wykopx** [comment]
Dzięki :) 
zobaczymy co z tego wyjdzie

**Comment by lukaszpolowczyk** [comment]
@wykopx Zainstalowałem rozszerzenie Stylus prosto z repo, z już dodaną poprawką do master, i wtedy da się zainstalować twój styl, instaluje się bez błędu.
Ale wydane oficjalnie jeszcze nie jest. Nie wiem kiedy wydadzą.

**Comment by dracorp** [comment]
@lukaszpolowczyk A co z layout.css.has-selector.enabled?

**Comment by lukaszpolowczyk** [comment]
@dracorp No to jest ta flaga. Za flagą `layout.css.has-selector.enabled` którą trzeba ustawić w `about:config`, jest CSS `:has()`. Ale od wersji 103, a ESR (wersja z przedłużonym wsparciem) jest w wersji 102.

**Comment by wykopx** [comment]
@dracorp 
> A co z layout.css.has-selector.enabled?

Nic. Robiłem testy na samym początku i włączenie tej flagi w tym przypadku nic nie zmieniło, nadal obsługa :has() a w szczególności trochę bardziej zaawansowanych - w Firefoxie nie działała. To jest flaga eksperymentalna. 

A pamiętajmy, że nie chodzi wyłącznie o sam podstawowy selector :has() ale o wszystkie kombinacje z nim związane: 

https://wpt.fyi/results/css/selectors/has-basic.html?label=experimental&label=master&aligned&view=subtest

**Comment by lukaszpolowczyk** [comment]
@wykopx  No to sobie jeszcze popracują najwyraźniej. :D

**Comment by wykopx** [comment]
Ja Ciebie też o coś prosiłem i nadal czekam.

**Comment by lukaszpolowczyk** [comment]
@wykopx  O co? :O :D

**Comment by lukaszpolowczyk** [comment]
@wykopx No napisz o co prosiłeś i czekasz? :D

**Comment by wykopx** [comment]
@lukaszpolowczyk @dracorp 

Firefox zaimplementował obsługę :has() 😁

https://github.com/wykopx/WykopX/wiki/%F0%9F%9A%AB-Problemy:-Mozilla-Firefox
https://github.com/wykopx/WykopX/wiki/Changelog#2450-firefox-121
