### ISSUE TITLE
'Zainstaluj Wykop XS, aby móc zmieniać tagi' mimo zainstalowania XD

### ISSUE THREAD

**Issue by ireun** [wykopx/WykopX#124]
Hej, mam zainstalowane oba skrypty, X oraz XS, mimo wszystko na stronach tagów widzę w/w komunikat. Nie do końca rozumiem o co chodzi.

**Comment by wykopx** [comment]
https://wykop.pl/wpis/71196515/hej-mala-aktualizacja-dla-uzytkownikow-skryptu-wyk
