### ISSUE TITLE
Rozciągnięte filmiki

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#127]
Jest:
![312321321](https://github.com/wykopx/WykopX/assets/125213230/799a42f6-4031-494a-895c-84ec3f56e775)

A powinno być:
![rwetertrt](https://github.com/wykopx/WykopX/assets/125213230/df84419a-8447-436a-9304-354f16551263)

Link: https://wykop.pl/link/7105335/stany-zjednoczone-podjely-decyzje-w-sprawie-mysliwcow-dla-ukrainy-wiadomosci

**Comment by wykopx** [comment]
Jest:

![image](https://github.com/wykopx/WykopX/assets/123825950/b5e6f992-88af-486e-b371-9c5554e9d272)

**Comment by SPSPSP10000** [comment]
U mnie jest rozciągnięte hmm...
