### ISSUE TITLE
✅ Wyjustowanie opisu znaleziska

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#13]
Przydałaby się opcja "wyjustowania" opisu znaleziska (tekst wyrównany do prawej i do lewej).

**Comment by wykopx** [comment]
Zrobione, działa całkiem ładnie. Dzięki za tę propozycję :)

![image](https://user-images.githubusercontent.com/123825950/218546515-d1e2a6df-e0d5-4843-b88c-d2b02567591b.png)
