### ISSUE TITLE
Zmiana treści oznaczającej zablokowanego użytkownika na jego login 

### ISSUE THREAD

**Issue by Ozjasz-Goldberg** [wykopx/WykopX#134]
Czasami mam kogoś na czarno, ale zdarza mu się napisać rzadko coś sensownego.

Przydałoby się zamiast napisu "komentarz użytkownika z czarnej listy" przy ukrytym komentarzu dać "login-użytkownika + #czarnolisto albo + #zablokowany

Wtedy np. wiem, że nie ma co rozwijać komentarzy poliwody czy opp0, ale już innego Mirka, który chwilowo spamował można podejrzeć i zadecydować o odblokowaniu (jak mu spamstorm przejdzie).

**Comment by wykopx** [comment]
Gdyby to było możliwe to już dawno bym to tak zrobił. Niestety - wykop nie wczytuje żadnych danych komentarza, który oznacza jako zablokowany (nawet jeśli to nie użytkownik jest zablokowany tylko w treści jest blokowany hashtag). 

Wykop wstawia tylko jeden element z informacją, że komentarz jest od zablokowanego użytkownika i nic więcej. 

Dopiero po kliknięciu (rozwinięciu) komentarza wczytywane sa informacje o autorze i treści. 

Do mementu kliknięcia nie mamy o nim żadnych informacji :(

Idiotyczne, ale niestety tak jest
