### ISSUE TITLE
Mirkoukrywacz (opcja zmiany położenia przycisku "Ukryj")

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#14]
Byłoby fajnie jakby można było zmienić to, gdzie ten przycisk jest (każdy sam by wybrał, czy woli w tym czy w innym miejscu). Proponowałbym, aby była możliwość wybrania, aby był z lewej strony od "plusów".

**Comment by wykopx** [comment]
Nie chce umieszczac go koło plusów, bo pewnie wiele osob klikaloby go niechcący zamierzając zaplusować komentarz. Dlatego ten przycisk musi być zdala od innych. A nie tuż obok. Dlatego tez nie umiescilem go kolo przycisków "Odpowiedz" i "Ulubione" tylko z takim dużym marginesem..


Myślałem czy by nie dodać go do menu akcji:

![image](https://user-images.githubusercontent.com/123825950/218330857-c81f906e-ae64-43fd-b3e8-04aac26607e2.png)

**Comment by SPSPSP10000** [comment]
Myślę, że jakby był wybór byłoby super np. domyślnie jest tam gdzie go umieściłeś, ale gdy ktoś chce go np. obok plusów to wtedy wybiera sobie opcję, że przycisk "Ukryj" ma być "obok plusów" - ukrywanie w "menu akcji" to zły pomysł - ja dużo ukrywam i to musi być proste i szybkie, klik i już... ew. też można by dać taką opcję do wyboru, chociaż raczej mało kto by z niej korzystał wg mnie.

**Comment by wykopx** [comment]
Niestety wyjątkowo akurat w tym przypadku muszę ten przycisk umieścić w jednym konkretnym miejscu, więc nie da się zrobić możliwości wyboru jego umiejscowienia. Pomyślę jeszcze nad tym gdzie on bedzie najlepiej pasował. Trzeba jeszcze wziac pod uwage, ze bedzie sie tez znajdował przy kazdym znalezisku, wiec jego położenie musi być jenolite - w tym samym miejscu i we wpisach i w znaleziskach.
