### ISSUE TITLE
[FEATURE REQUEST] Więcej opcji paginacji

### ISSUE THREAD

**Issue by grappas** [wykopx/WykopX#142]
Paginacja główniej, mirko, komentarzy... W starej wersji można było sobie to skryptami ograrnąć.

**Comment by wykopx** [comment]
> Paginacja główniej, mirko, komentarzy

Super opis. Prawie wiadomo o co chodzi.

**Comment by grappas** [comment]
Nie ma potrzeby być sarkastycznym. Już spieszę tłumaczyć:

- Tutaj błąd z mojej strony - chodzi o repaginację
- Polega to na doklejaniu kolejnej strony do bieżącej po dojechaniu/zbliżaniu się do jej końca tak, aby nie było potrzeby klikania następnej.
![obraz](https://github.com/wykopx/WykopX/assets/1036957/ef0e7dba-418e-4715-81ed-86d7a9d42043)
- Tyczy się to głównej, mirko i komentarzy.

**Comment by grappas** [comment]
@wykopx czy pomysł jest rozważany?
