### ISSUE TITLE
we wpisach które mają zdjęcie/ankietę nie mogę wejść w tag, jeśli nazwa tagu jest w tej samej linijce co tekst 

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#143]
jeśli wpis ma załączone zdjęcie + tekst z nazwą tagu w jednej linijce wtedy najechanie na nazwę tagu w celu przejścia do niego jest niemożliwe - nazwa tagu się nie podkreśla

jeśli taki sam wpis ma nazwę tagu napisaną w oddzielnej linijce wtedy wszystko działa normalnie 
![image](https://github.com/wykopx/WykopX/assets/127026337/8c7dae93-c6f4-4df0-9079-7ffe8b687541)

możliwe że jest to błąd wersji 2.22.2 - lub kliknąłem jakąś opcję omyłkowo [?]

**Comment by wykopx** [comment]
Potwierdzam, ten błąd jest już chyba od jakiegoś czasu. Naprawię niedługo, dzięki za zgłoszenie ;)

**Comment by wykopx** [comment]
Naprawione w wersji 2.36.0
