### ISSUE TITLE
Czarnolistowanie słów kluczowych w tytułach znalezisk

### ISSUE THREAD

**Issue by grappas** [wykopx/WykopX#145]
Np. filtrowanie wszystkich znalezisk zawierających słowo "Pilne!"

**Comment by wykopx** [comment]
Bardzo fajny pomysł! Dzięki

**Comment by wykopx** [comment]
@grappas jakiś pomysł jakie jeszcze mogłyby to być słowa? "PILNE" faktycznie jest bardzo dobrym przykładem użycia takiego słowa. Jakieś inne wpadają do głowy?

**Comment by grappas** [comment]
Fajnie byłoby, gdyby użytkownik mógł sobie samemu definiować jakie słowa wpadają na czarno.

Kiedyś można było spotkać często słowo "zmasakrował", które było nagminnie nadużywane nieadekwatnie do znaczenia słowa.

**Comment by wykopx** [comment]
@grappas tak tak, zrozumiałem wcześniej, ze słowo "PILNE" miałoby być konfigurowalne. "zmasakrował" faktycznie jest ciekawe. Jeszcze jakieś? Im więcej wizji do czego taka funkcja mogłaby służyć pozwoli mi lepiej ją zaprojektować.

**Comment by grappas** [comment]
wg upodobań

AFERA
UWAGA

Możnaby jeszcze wykorzystać do czarnolistowania wykopów zawierające słowo "Janusz" w czasie, kiedy mamy przepełnioną główną Januszem Korwin-Mikke ( ͡° ͜ʖ ͡°).
Albo wywalić słowa "PiS", "KO" na wypadek ludzi nie potrafiących używać tagu #polityka , albo w momencie kiedy nie interesują nas cringe'owe heheszki polityczne.

Najlepiej, żeby to wyglądało w ten sposób, że dodajemy linijka po linijce kolejno słowa, gdzie w ramach jednej linijki, żeby algorytm wyszukiwał kombinacji tych słów np.

Janusz, janusz, korwin, Korwin #tu ewentualnie dać ticka czy case-sensitive tutaj wywalane są stricte w kombinacji **janusz**a **korwin**-mikkego
"UWAGA AFERA" # tu wywalanie są konkretne stringi dosłownie

**Comment by wykopx** [comment]
OK, zrobione ;)
Na razie na próbę tylko jedno słowo, zobaczymy czy będzie warto rozwijać to na więcej słów.
- możliwość ukrycia znalezisk ze słowem kluczowym
- możliwość wyróżnienia znalezisk ze słowem kluczowym
- możliwość przeniesienia znalezisk ze słowem kluczowym na początek listy znalezisk

https://github.com/wykopx/WykopX/wiki/Changelog#2250-s%C5%82owa-kluczowe

![image](https://github.com/wykopx/WykopX/assets/123825950/8261dd00-2a4c-4350-9423-b7019387cae0)
