### ISSUE TITLE
Obrazek z lewej strony (strona główna i wykopalisko)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#15]
Byłoby fajnie, jakby obrazek na stronie głównej i wykopalisku był z lewej strony (opcja do wyboru: "obrazek z prawej" lub "obrazek z lewej") - kiedyś była taka opcja i mi działała dobrze, ale została usunięta, mam nadzieję, że powróci.

**Comment by wykopx** [comment]
No.. to prawda. Muszę w koncu przywrócić tę funkcję.. bo to była jedna z pierwszych funkcji jaką zrobiłem, ale musiałem ją na jakiś czas wyłączyć.

**Comment by SPSPSP10000** [comment]
U mnie działała idealnie... ale obstawiam, że był ku temu powód, aby ją wyłączyć... ale fajnie jakby wróciła ;)

**Comment by SPSPSP10000** [comment]
To chyba można już zamknąć.
