### ISSUE TITLE
Niektóre skróty na pasku nie działają

### ISSUE THREAD

**Issue by grozn-y** [wykopx/WykopX#154]
Cztery pierwsze ikony działają poprawnie (tryb nocny-dzienny, mikroblog, obserwowane, skrzynka odbiorcza), jednak następne dwa (dzwonek z powiadomieniami, obserwowane hasztagi), nie działają, wygląda na to, że są jedynie ikoną, gdyż po kliknięciu na nie nic się nie dzieje, a dymek z ilością obserwowanych tagów jest zdublowany.
![image](https://github.com/wykopx/WykopX/assets/119747443/bfa797dc-84fb-4f01-bc5e-ce5ff6755819)

**Comment by wykopx** [comment]
Naprawione w wersji 2.32.3 
https://github.com/wykopx/WykopX/wiki/Changelog#2323
