### ISSUE TITLE
Złe wyświetlanie na stronie mobilnej

### ISSUE THREAD

**Issue by grappas** [wykopx/WykopX#158]
![IMG_20231202_010100.jpg](https://github.com/wykopx/WykopX/assets/1036957/f4e2c58b-5ff6-4e78-983c-ec357b00b985)

**Comment by wykopx** [comment]
Potrzebuję trochę wiecej informacji 
Jaka to przeglądarka?
Przy jakich ustawieniach się tak rozjeżdza, a przy jakich nie?
@grappas

**Comment by grappas** [comment]
Firefox Nightly na Android
Ustawienia są takie jak były out-of-the-box. Nie testowałem innych ustawień - strasznie upierdliwie się je klika na telefonie.

**Comment by grappas** [comment]
"Wyjustowany opis znaleziska" Powoduje przedłużenie opisów. 

Szukam jeszcze czemu dolna belka świruje i dodanie znaleziska.

**Comment by wykopx** [comment]
> Firefox Nightly na Android Ustawienia są takie jak były out-of-the-box. Nie testowałem innych ustawień - strasznie upierdliwie się je klika na telefonie.

Po 1. Firefox nie umie jeszcze obsługiwać :has() więc nie jest wspierany 
https://github.com/wykopx/WykopX/wiki/%F0%9F%9A%AB-Problemy:-Mozilla-Firefox/

- ale w końcu od miesiaca sie cos ruszyło i jest szansa, ze niedługo będzie.
Po 2. Out of the box powinno wszystko bardzo ladnie smigać na telefonie (nie na Firefoxie) po dwarunkiem włączenia 
ustawienia "Smartfon" zamiast "Komputer"

![image](https://github.com/wykopx/WykopX/assets/123825950/8e01c28f-3dc4-48fd-a7d3-63c3e5e24c95)

Z racji tego, że rozjeżdzanie się jest winą Firefoxa zamykam temat i czekamy aż mozilla w końcu zaimplementuje selektor :has()

**Comment by wykopx** [comment]
@grappas 
Powinno już działać :)

https://github.com/wykopx/WykopX/wiki/%F0%9F%9A%AB-Problemy:-Mozilla-Firefox
https://github.com/wykopx/WykopX/wiki/Changelog#2450-firefox-121
