### ISSUE TITLE
Mirkoukrywacz - cofanie cofnięcia

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#17]
Czy obecnie jest taka możliwość, aby cofnąć cofnięcie? Przypadkowo ukryłem sobie wpis i nie mogę tego cofnąć... może warto byłoby rozważyć przycisk "cofnij ukrycie"? Sam do końca nie wiem, jak miałoby to wyglądać hmm... ale posyłam pomysł...

**Comment by wykopx** [comment]
![image](https://user-images.githubusercontent.com/123825950/218330967-55f7f603-7db5-4ff6-83ee-c9c7a9ee1d1e.png)

**Comment by SPSPSP10000** [comment]
Ok dzięki :)

**Comment by SPSPSP10000** [comment]
PS. Można by wprowadzić opcję do zaznaczenia "czyść mirkoukrywacza po 24 godzinach".

**Comment by SPSPSP10000** [comment]
Nie wiem, czy widziałeś mój post, ale myślę, że pomysł dobry.
