### ISSUE TITLE
Mikroskopijne obrazki na mikroblogu

### ISSUE THREAD

**Issue by ireun** [wykopx/WykopX#176]
![image](https://github.com/wykopx/WykopX/assets/695818/b7f82bca-818a-42fe-bd55-c1252526b32c)

Is it a feature or a bug? Nie znalazłem w opcjach żadnej opcji żeby temu zaradzić

Wersja 2.45.1

**Comment by wykopx** [comment]
Naprawione w wersji 2.45.2
