### ISSUE TITLE
"Mój wykop" - nie da się go ukryć

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#18]
Pomimo że wyłączyłem wszystko co związane z "Mój wykop" wciąż go widzę, czy inni też tak mają, że nie są w stanie tego "napisu" schować?

**Comment by wykopx** [comment]
Wklej proszę screenshot z wyglądem strony i przyciskiem

**Comment by SPSPSP10000** [comment]
![1111111111111](https://user-images.githubusercontent.com/125213230/218330789-8f0ec31f-80f8-49dd-8d9f-774955552483.png)
![122](https://user-images.githubusercontent.com/125213230/218330795-264d2b9d-182d-423b-adbe-6f8d61a66f57.png)

**Comment by wykopx** [comment]
A pokaż mi jeszcze tę część konfiguracji

![image](https://user-images.githubusercontent.com/123825950/218499602-13cf72b1-1572-46df-ae76-c842a46cf2c3.png)

**Comment by wykopx** [comment]
Zgaduję, że masz włączoną opcję:
![image](https://user-images.githubusercontent.com/123825950/218499955-0ce1ce3a-8e22-4f05-8f43-e4d26b6b4ef3.png)

a w klasycznym wykopie był przycisk Mój Wykop :)

**Comment by SPSPSP10000** [comment]
W trybie incognito jest u mnie ok... poszukam w czym problem.
