### ISSUE TITLE
✅ Kliknięcie w logo wykopu odświeża całą stronę

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#19]
Byłoby fajnie, jakby: gdy jest się na stronie głównej i kliknie się w ikonkę "Wykop.pl", aby odświeżało stronę (tak było na starym wykopie i można było tak sobie uaktualniać ilość "wykopów" na głównej.

**Comment by wykopx** [comment]
Zrobione, v.2.7.2

https://github.com/wykopx/WykopX/wiki/Changelog#272

**Comment by SPSPSP10000** [comment]
Coś jest nie tak z odświeżaniem. Jak uruchomię chrome i wejdę na wykop i nacisnę na baner "wykop.pl" to odświeży stronę, ale po odświeżeniu już odświeżanie nie działa. Czy to jest związane z tym, że muszę czekać na Wykop XS w tej samej wersji, czyli 2.7.3? Czy to jakiś po prostu błąd? Mikroblog w ogóle nie odświeża...

**Comment by wykopx** [comment]
Nie mogę potwierdzić. Wszystko działa tak jak należy
![Uploading refresh page.gif…]()

**Comment by SPSPSP10000** [comment]
Ten problem jest powiązany z tym:
https://github.com/wykopx/WykopX/issues/42

Jeżeli są te "dodatkowe opcje w profilu" to u mnie działa idealnie, ale jak zniknął, to odświeżanie nie działa. To takie info.
