### ISSUE TITLE
Ukrywanie i gruba zielona obramówka

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#20]
Nie wiem o co chodzi, ale gdy ukryję coś za pomocą mirkoukrywacza to zamiast się ukrywać robi mi się taka gruba zielona ramka, nie wiem o co chodzi... może coś kliknąłem w opcjach, czego nie powinienem?
![2222222222](https://user-images.githubusercontent.com/125213230/218332700-d78088c2-ee79-4b53-9fc4-68b9d07f6d86.png)

**Comment by wykopx** [comment]
![image](https://user-images.githubusercontent.com/123825950/218369967-0a066a4d-4580-46ef-a524-2e39c7452484.png)

**Comment by SPSPSP10000** [comment]
Właściwie to "Tryb developers­ki do testowania" to powoduje - musiałem przez przypadek kliknąć. Thx za info.
