### ISSUE TITLE
✅ #Tags are case sensitive 

### ISSUE THREAD

**Issue by wykopx** [wykopx/WykopX#21]
✅ https://wykop.pl/@m__b/#WYKOP (Alias URL Wykop X)
✅ https://wykop.pl/szukaj/wszystkie/@m__b?tags=WYKOP  
-- poprawnie wyświetla wszystkie wpisy @m__b z tagiem #wykop 

❌ https://wykop.pl/tag/WYKOP  
-- pokazuje tag autorski, ale nie wyświetla wpisów z #wykop tylko z #WYKOP 
❌ https://wykop.pl/tag/WYKOP/znaleziska
❌ https://wykop.pl/tag/WYKOP/wpisy
   
❌ https://wykop.pl/tag/Medycyna  
-- wyświetla z tagami #Medycyna zamiast #medycyna

Inne przykłady:
1. Tagi #heheszki i #Heheszki przenoszą na dwie rozne strony, a powinny na #heheszki
2. Tagi #covid #COVID wyświetlają zupełnie różne wpisy/znaleziska

Błąd zauważył: @Dokkblar  we wpisie: https://wykop.pl/wpis/70397415/

![image](https://user-images.githubusercontent.com/123825950/218473098-471d3818-1ed4-4d5e-9507-50124ba57494.png)

Wykop XS naprawia ten błąd:
```

(async () => {
	let pathname = new URL(document.URL).pathname;
	let pathnameArray = pathname.split("/");
	if (pathnameArray[1] == "tag" && /[A-Z]/.test(pathnameArray[2])) {
		pathnameArray[2] = pathnameArray[2].toLowerCase();
		let newPathname = pathnameArray.join("/");
		window.location.replace("https://wykop.pl" + newPathname);
}});
```

| Błędny URL  | Wykop X otwiera |
| ------------- | ------------- |
| ❌ https://wykop.pl/tag/WYKOP  |  ✅ https://wykop.pl/tag/wykop  |
| ❌ https://wykop.pl/tag/WYKOP/znaleziska  |  ✅ https://wykop.pl/tag/wykop/znaleziska  |
| ❌ https://wykop.pl/tag/WYKOP/wpisy  |  ✅ https://wykop.pl/tag/wykop/wpisy  |

Jeśli natkniesz się na wpis/komentarz, w którym ktoś użył wielkiej litery, lub wpiszesz ręcznie tag z wielkiej litery - Wykop przekieruje Cię do strony tagu, na której będą treści z tagu z wielką literą - najczęściej są to puste strony, np.    
https://wykop.pl/tag/WYKOP/wpisy/     

Wykop X domyślnie naprawia ten błąd i nawet jeśli klikniesz w tag #WYKOP zostaniesz przeniesiony na  
https://wykop.pl/tag/wykop
  
Uwaga. ❎ Do działania niezbędny jest skrypt [Wykop XS](https://github.com/wykopx/WykopX/wiki/Wykop-XS)  

![Animation](https://user-images.githubusercontent.com/123825950/221016513-ced30271-634d-437a-9b9c-de155b520f09.gif)
https://streamable.com/ftm7fj

![image](https://user-images.githubusercontent.com/123825950/221005359-3bdd3fa9-2b3a-4b29-99e8-e89fb41cb4a5.png)

**Comment by SPSPSP10000** [comment]
Dopracowany ten wykop, nie powiem :P

**Comment by wykopx** [comment]
✅ https://wykop.pl/szukaj/wszystkie/@m__b?tags=WYKOP 

![image](https://user-images.githubusercontent.com/123825950/221001834-f37329f5-3f2b-43fe-8b64-36d2589eae36.png)

**Comment by wykopx** [comment]
❌ https://wykop.pl/tag/WYKOP --> pokazuje tag autorski, ale nie wyświetla wpisów z #wykop tylko z #WYKOP 


![image](https://user-images.githubusercontent.com/123825950/221002221-e08cef6b-2944-4daf-8486-f1d497c3553a.png)
