### ISSUE TITLE
Hity (nie da się ukryć)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#23]
Nie jestem w stanie ukryć przycisku "Hity" na stronie głównej. Ustawiłem wszystkie opcje jak trzeba we wtyczce, abym ich nie widział, ale to nic nie daje, to samo tyczy się "Mój wykop".

PS. Jako ciekawostkę dodam, że ukrywanie przycisku "Wykopalisko" działa jak należy.

**Comment by SPSPSP10000** [comment]
Włączona.

**Comment by wykopx** [comment]
Więc wyłącz.
