### ISSUE TITLE
Rozciągnięcie znalezisk + wycentrowanie wpisów

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#24]
Przydałaby się możliwość ustawienia konkretnej długości wpisów na głównej (szerokości) (może być to zrobione "procentowo") + możliwość ustawienia, aby wpisy były wycentrowane na środku, a nie do lewej.

**Comment by wykopx** [comment]
Częściowo jest już to zrobione i działa.

![image](https://user-images.githubusercontent.com/123825950/229003999-7615c8e6-6796-41d1-9e3a-3d0efe8226a8.png)


Będę jeszcze całkowicie przenosił layout strony na CSS grid, żeby były większe możliwości manipulacją położenia i rozmieszczenia wszystkich elementów.
