### ISSUE TITLE
Liczba nowych wykopalisk (nie działa jak kiedyś)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#25]
"Liczba nowych wykopalisk" nie działa jak kiedyś. Kiedyś zmiana opcji coś robiła, teraz nie. Mogę jedynie tak mieć. Inne warianty nie działają (a kiedyś działy).
![222222](https://user-images.githubusercontent.com/125213230/218513096-31193ade-3020-4ddf-b81f-0fdb56f9d42f.png)

**Comment by wykopx** [comment]
![image](https://user-images.githubusercontent.com/123825950/218516592-6a9563c7-7761-45f2-83f8-121b4f0bd32f.png)

![image](https://user-images.githubusercontent.com/123825950/218516462-3cad529c-92e8-4d2a-ab86-4ceaa544aa3d.png)



![image](https://user-images.githubusercontent.com/123825950/218516696-eb2843cb-2347-49cd-aec4-a2ab9535c2d9.png)

![image](https://user-images.githubusercontent.com/123825950/218516662-7a73e8a4-1867-45da-b910-60d622f416e2.png)


Działają wszystkie warianty oprócz Liczby wykopalisk w stylu Wykop 1.0, ktory przestał dzialac bo Wykop cos pozmieniał.

Bedzie przywrócone.

**Comment by wykopx** [comment]
Nic nie zmieniałem, ale u mnie działa.
