### ISSUE TITLE
Przenoszenie pod wpis

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#27]
Przenoszeni do konkretnego wpisu działa, ale mogłoby przenosić lekko niżej, aby nie było widać tego, co zaznaczyłem strzałką.
![1111111111111](https://user-images.githubusercontent.com/125213230/218535698-7918a536-d11d-4d9f-9610-4dce6e4543ec.png)

**Comment by wykopx** [comment]
Nie mogę potwierdzić. U mnie przenosi idealnie pokazując na górze komentarz, który wołał

![image](https://user-images.githubusercontent.com/123825950/218558153-5a9f043b-60ee-4337-b6e8-b210304c684a.png)

Sprawdź ustawienia przeglądarki, bo tu akurat wykopowi programiści wszystko dobrze napisali.
