### ISSUE TITLE
"Dodaj znak + przed liczbą plusów" oraz "Styl plusów i minusów"

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#28]
Nie działa mi ta opcja, na stałe jest "plus", ale nie da się go wyłączyć. "Styl plusów i minusów" u mnie nic nie robi niezależnie co ustawię hmmm...

**Comment by wykopx** [comment]
Wyłącz opcję `💻📱 Włącz opcje stylizując­e na Wykop 1.0`

![image](https://user-images.githubusercontent.com/123825950/218541824-ddbbf79c-6692-4f63-822d-e3111caf7799.png)

**Comment by SPSPSP10000** [comment]
Ok dzięki, działa :)
