### ISSUE TITLE
Przycisk "wyłącz wszystkie" w panelu ustawień WykopX. Żeby zrestartować do domyślnych (dla wykopu, nie dla WykopX) wszystkie ustawienia

### ISSUE THREAD

**Issue by look997** [wykopx/WykopX#32]
Przycisk "wyłącz wszystkie" w panelu ustawień WykopX. Żeby zrestartować do domyślnych (dla wykopu, nie dla WykopX) wszystkie ustawienia.

**Comment by wykopx** [comment]
Niestety na ten moment jest to niewykonalne. Gdyby było już dawno bym taką opcję dodał. 

Ale wystarczy wyłączyć w okienku Wykop X i przeciez wtedy zadne style nie są zastosowane:

![image](https://user-images.githubusercontent.com/123825950/218591857-6174d1f7-cef1-4cd5-8e89-f1230311518f.png)

**Comment by lukaszpolowczyk** [comment]
@wykopx Ale chodzi o taki punkt startu, że wyłączasz wszystko do poziomu jaki jest w wykopie bez stylu, a włączasz tylko jakieś np. 5 opcji, które cię interesują. Żeby nie musieć całej długiej listy opcji przeglądać i przeklikiwać, bo jest tego dużo w twoim stylu.

**Comment by look997** [comment]
@wykopx Ale chodzi o taki punkt startu, że wyłączasz wszystko do poziomu jaki jest w wykopie bez stylu, a włączasz tylko jakieś np. 5 opcji, które cię interesują. Żeby nie musieć całej długiej listy opcji przeglądać i przeklikiwać, bo jest tego dużo w twoim stylu.

**Comment by wykopx** [comment]
Wykop X Blank - wersja Wykop X z wszystkimi wyłączonymi funkcjami

https://userstyles.world/style/8419/wykop-x-blank

**Comment by lukaszpolowczyk** [comment]
@wykopx Nadal za dużo domyślnie zmienia. Style pozmieniane, gryzie się z "Wykop the best style".
