### ISSUE TITLE
Zmiana czcionki/odstępów/rozmiarów czcionek

### ISSUE THREAD

**Issue by ultrasoniccc** [wykopx/WykopX#35]
Możliwość zmiany czcionek i odstępów między wierszami jak w innym dodatku do wykopa xd

![image](https://user-images.githubusercontent.com/125352319/218686953-a1e7b4a3-72ee-4dee-85b9-7eacf31191ef.png)

**Comment by wykopx** [comment]
Dzięki za dobry pomysł! 

Wprowadzone w 2.9.3

https://github.com/wykopx/WykopX/wiki/Changelog#293


# [2.9.3]  

Funkcja `⭐ Zmień rozmiar tekstu` została napisana całkowicie na nowo
- po ustawieniu własnego rozmiaru czcionek zmieniają się wszystkie treści na wykopie (teksty wpisów, komentarzy, tytuły znalezisk, loginy, przyciski etc.)
- w tej wersji około tylko 5% elementów (np. liczba plusów) nie zmienia swojej wielkości - zostanie to poprawione w przyszłych aktualizacjach

Masz możliwośc wyboru 12 różnych rozmiarów - od najmniejszego do ogromnego. Przy nazwie wielkości podana jest podstawowa wielkość fontu, która stosowana jest do większości elementów. Elementy z mniejszym/większym fontem zostaną automatycznie przeskalowane bazując na ustawieniu podstawowej wielkości.

![image](https://user-images.githubusercontent.com/123825950/221410711-7ca82247-582d-4263-8c63-0c82d28069a5.png)

Przykłady:

Domyślna wielkość Wykop 2.0 to 16px:

![image](https://user-images.githubusercontent.com/123825950/221410862-48969e10-28bc-4c57-9612-2c1a8a5bf9ad.png)

Przy ustawieniu `19px - duży`:   

![image](https://user-images.githubusercontent.com/123825950/221410837-23769022-9d69-4584-b8fc-9ef080f25b7e.png)

Przy ustawieniu `12px - mały`:   

![image](https://user-images.githubusercontent.com/123825950/221410926-810d7c99-66a0-404d-a62f-34c090f04b9c.png)
