### ISSUE TITLE
Ukrywanie komentarza, gdy go zminusuję

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#36]

**Comment by wykopx** [comment]
Zrobione w. 2.10.2
https://github.com/wykopx/WykopX/wiki/Changelog#2102

https://wykop.pl/wpis/70555585/wykop-x-aktudalizacja-wersja-2-10-2-wykopwnowymsty

Funkcja `⭐ Ukryj zminusowan­e komentarze w znaleziska­ch`

Wariacja funkcji znanej ze starego wykopu - po zaminusowaniu komentarza jest on ukrywany (zwijany) i wyszarzony.
[[Reqest 36](https://github.com/wykopx/WykopX/issues/36)]

![ukry zminusowane komentarze](https://user-images.githubusercontent.com/123825950/221558587-2544e8bc-c77e-4a93-8f6d-441908780aa7.gif)
