### ISSUE TITLE
Przycisk "Otwórz następne nieprzeczytane powiadomienie"

### ISSUE THREAD

**Issue by houk001** [wykopx/WykopX#4]
Tutaj była wyciągana pełna ilość powiadomień oraz np był super guzik otwórz nastepne nieprzeczytane powiadomienie :D 

// ==UserScript==
// @name       krejdowe menu
// @namespace  http://www.wykop.pl/*
// @version    1.2
// @description  Dodaje ikony w górnej części strony, aby ułatwić nawigację po Wykopie
// @match      *://www.wykop.pl/*
// @copyright  krejd
// ==/UserScript==

// Checks protocol
var wykopProtocol = window.location.protocol;

// Goes to next unread tag
$('body').on('click', '#nextTag', function(event) {
    event.preventDefault();

    // Dblclick button to get ajax working as
    // it needs to scrape unread notification urls
    $('body').append('<style id="niewidacheheszki">.menu-list { display:none !important; }</style>');
    $('.notification.m-tag > a.ajax').trigger('click');

    // Checks if ajax complete
    checkIfShownNote = setInterval(function() {
        if(jQuery.active === 0) {
            clearInterval(checkIfShownNote);
            $('body').trigger('click');

            $('.notification.m-tag .menu-list li:first a').each(function(index,value) {
                if($(this).attr('href').match(/wpis/i)) {
                    hashHref = $(this).attr('href');
                    window.location.href = hashHref;
                }
            });

            $('#niewidacheheszki').remove();
        }
    }, 50);
});

// Goes to next unread notification
$('body').on('click', '#nextNote', function(event) {
    event.preventDefault();

    // Dblclick button to get ajax working as
    // it needs to scrape unread notification urls
    $('body').append('<style id="niewidacheheszki">.menu-list { display:none !important; }</style>');
    $('.notification.m-user > a.ajax').trigger('click');

    // Checks if ajax complete
    checkIfShownNote = setInterval(function() {
        if(jQuery.active === 0) {
            clearInterval(checkIfShownNote);
            $('body').trigger('click');

            $('.notification.m-user .menu-list li:first a').each(function(index,value) {
                if($(this).attr('href').match(/wpis/i) || $(this).attr('href').match(/konwersacja/i) || $(this).attr('href').match(/comment/i)) {
                    hashHref = $(this).attr('href');
                    window.location.href = hashHref;
                }
            });

            $('#niewidacheheszki').remove();
        }
    }, 50);
});

// Append new buttons to Wykop interface
// Append new buttons to Wykop interface
// Append new buttons to Wykop interface

$('div#nav ul.clearfix:last > li.notification.m-user').before($('<li/>', {
    id: 'nextNote',
    html: '<a class="dropdown-show" href="'+wykopProtocol+'//www.wykop.pl/powiadomienia/do-mnie/"><i class="fa fa-envelope"></i><b class="" id="hashtagsNotificationsCount" style="background:#FF5917; font-size:0; display:block; padding:1px; top:22px; right:20px; min-width:10px; width:10px; min-height:10px; height:10px; border-radius:5px; overflow:hidden;">&nbsp;</b></a><div class="notificationsContainer"></div>',
    class: "notification m-user krejd-nextnotification",
    title: "Czytaj następne powiadomienie",
    alt: "Czytaj następne powiadomienie"
}));

$('div#nav ul.clearfix:last > li.notification.m-tag').before($('<li/>', {
    id: 'allTags',
    html: '<a class="dropdown-show hashtag" href="'+wykopProtocol+'//www.wykop.pl/powiadomienia/unreadtags/"><b class="" id="hashtagsNotificationsCount" style="background:#924396; font-size:0; display:block; padding:1px; top:22px; right:16px; min-width:10px; width:10px; min-height:10px; height:10px; border-radius:5px; overflow:hidden;">&nbsp;</b>#</a><div class="notificationsContainer"></div>',
    class: "notification m-tag krejd-alltags",
    title: "Pokaż nieprzeczytane wpisy z tagów",
    alt: "Pokaż nieprzeczytane wpisy z tagów"
}));

$('div#nav ul.clearfix:last > li.notification.m-tag:not(.krejd-alltags)').before($('<li/>', {
    id: 'nextTag',
    html: '<a class="dropdown-show hashtag" href="'+wykopProtocol+'//www.wykop.pl/powiadomienia/tagi/"><b class="" id="hashtagsNotificationsCount" style="background:#FF5917; font-size:0; display:block; padding:1px; top:22px; right:16px; min-width:10px; width:10px; min-height:10px; height:10px; border-radius:5px; overflow:hidden;">&nbsp;</b>#</a><div class="notificationsContainer"></div>',
    class: "notification m-tag krejd-nexttag",
    title: "Czytaj następny tag",
    alt: "Czytaj następny tag"
}));

**Comment by wykopx** [comment]
> Tutaj była wyciągana pełna ilość powiadomień oraz np był super guzik otwórz nastepne nieprzeczytane powiadomienie :D

Nic nie rozumiem. @houk001 możesz mi to jakoś lepiej opisać? Pamiętaj, że ja nie korzystałem z tego skryptu i nie wiem jak on działał. Dla Ciebie jego działanie jest oczywiste, a dla mnie nie.  

Zrób zrzut ekranu nowego wykopa i narysuj co i gdzie miałoby być i co robić. 
PS. Co to w ogóle znaczy "Krejdowe"?

**Comment by houk001** [comment]
Tak ktoś nazwał ten dodatek. On dorabiał dodatkowe guziki tak jak twój po prawej na górze strony. Jeden z tych guzików to po kliknięciu przeładowywał stronę prowadząc do linka z powiadomienia nieprzeczytanego i jak skończyły się powiadomienia nieprzeczytane to przestawał działać.  z kodu powyzej guzik title: "Czytaj następne powiadomienie",


  A na guziku obok normalnym wyświetlał listę wszystkich powiadomień dlatego go załączyłem bo jak sam szukasz jak to zrobić z api to może tutaj znajdziesz info jak zrobił to ktoś przed Tobą. Tu własnei jak pisałem wcześniej pojawiała sie liczba wszystkich powiadomień  nawet do 100 dochodząca

**Comment by wykopx** [comment]
Krejdowe menu (nie działa)
https://greasyfork.org/pl/scripts/2210-krejdowe-menu

Krejd Power Menu (nie działa)
https://github.com/krejdster/wykop-powermenu
![image](https://github.com/wykopx/WykopX/assets/123825950/d116f271-9e84-4958-a693-d731a21d0ca4)

https://wykop.pl/wpis/30717079/wykop-powermenu-v2-00-wydane-hej-mireczki-po-ostat
