### ISSUE TITLE
Możliwość usunięcia przycisku "ulubione" w znaleziskach, komentarzach i mirko

### ISSUE THREAD

**Issue by ultrasoniccc** [wykopx/WykopX#41]
![image](https://user-images.githubusercontent.com/125352319/218970196-249255c6-11da-42f2-92b0-aa9179fdc5ea.png)

**Comment by wykopx** [comment]
Dodane w wersji 2.8.3

https://github.com/wykopx/WykopX/wiki/Changelog#283
