### ISSUE TITLE
Znikający "Wykop X" (kliknięcie w ikonkę profilową)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#42]
Raz jest raz nie ma... to powoduje problemy z odświeżaniem (ikonka wykop.pl)
![1111111111111](https://user-images.githubusercontent.com/125213230/218977355-75ac94ac-4184-4d15-93f1-91c39a190848.png)

**Comment by wykopx** [comment]
Wystarczy odświeżyć. Znam problem i w miarę możliwości będę probował go naprawić. Wynika z tego, że Wykop teraz działa jak prawdziwa aplikacja webowa, czyli nie otwiera nowych stron, tylko pobiera zawartość i wypełnia kontekst nowymi danymi. Stąd czasem Wykop XS się "wyłącza".

**Comment by SPSPSP10000** [comment]
Będzie to naprawione? U mnie wciąż jest z tym problem.

**Comment by SPSPSP10000** [comment]
Czasem wielokrotne odświeżanie nie pomaga... istotna loteria... no nic... mam nadzieję, że uda się rozwiązać kiedyś ten problem...

**Comment by wykopx** [comment]
Wiem wiem, kombinuję żeby coś z tym zrobić. Też mnie to irytuje :)

**Comment by SPSPSP10000** [comment]
To może nie powinno to być w sekcji "zamknięte"? I może ktoś na wykopie coś podpowie? ;)
