### ISSUE TITLE
Bug - ukryj liczbę wykopalisk nie działa

### ISSUE THREAD

**Issue by ultrasoniccc** [wykopx/WykopX#43]
![image](https://user-images.githubusercontent.com/125352319/218990013-926df339-41cf-4129-bf3b-3d997a38b891.png)

**Comment by wykopx** [comment]
Działa.

https://github.com/wykopx/WykopX/wiki/%E2%9D%93-Jak-w%C5%82%C4%85czy%C4%87-wygl%C4%85d-starego-wykopu
