### ISSUE TITLE
Dodanie opcji wyłączenia zmiany koloru przycisku "WYŚLIJ"

### ISSUE THREAD

**Issue by jendrush** [wykopx/WykopX#44]
Obecnie gdy pole do wpisania komentarza jest puste, przycisk jest szary. Gdy zaczniemy pisać treść komentarza i przerwiemy pisanie, robi się on niebieski, by znów zmienić kolor na szary podczas dalszego pisania. Chciałbym móc wyłączyć to dynamiczne zachowanie i mieć ten przycisk na stałe np. w niebieskim kolorze.

**Comment by wykopx** [comment]
Bardzo dobra uwaga, faktycznie te zmieniane kolory są irytujace.

**Comment by wykopx** [comment]
Zrobione, v. 2.7.7
