### ISSUE TITLE
Automatyczne powiadomienie na wykopie o nowej wersji Wykop X na Stylusie

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#46]
Gdy Wykop XS na tampermonkey ma nową wersję, to na wykopie pojawia się od razu powiadomienie w postaci paska na górze, czy dałoby radę zrobić coś podobnego dla Wykop X na Stylusie? Może to głupie pytanie, ale to fajna opcja przypominająca o aktualizacji. Nie wiem czy to technicznie możliwe, obstawiam, że pewnie nie, ale wolę spytać.

**Comment by wykopx** [comment]
Trochę czasu mi zajęło, żeby wymyślić jakis sposób na to powiadomienie o nowej wersji Wykopu XS i jakoś od razu wyszedłem z założenia, że na Wykop X do stylu się nie da tego zrobić... Ale jak teraz napisałeś ten komentarz to mnie olśniło, że to przecież banalnie proste do zrobienia xD

Czasem potrzeba takiego kopniaka w glowe, żeby się ocknąć xD

Dzięki!

**Comment by SPSPSP10000** [comment]
PS. Jak jest to takie banalne, to może pojawi się to w następnej aktualizacji? :)

**Comment by wykopx** [comment]
Może się pojawi, kto wie? :)

**Comment by SPSPSP10000** [comment]
Dałbym temu wysoki priorytet ;)

**Comment by wykopx** [comment]
@SPSPSP10000 w końcu się udało ;)  

https://github.com/wykopx/WykopX/wiki/Changelog#2300

![image](https://github.com/wykopx/WykopX/assets/123825950/a9179b4d-41ec-4426-9ecd-8f6501375677)
