### ISSUE TITLE
Mirkoukrywacz - dublowanie ukrytych postów

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#48]
Gdy 2x kliknę w "Wykop X - Mirkoukrywacz" w profilu, to ukryte wpisy się dublują... a później są 3x... itd...
![222222222222222](https://user-images.githubusercontent.com/125213230/220744167-ffd6cdef-2805-43b9-aa1e-b300ab940078.png)

**Comment by wykopx** [comment]
Naprawione od wersji 2.8.3
