### ISSUE TITLE
✅ Mirkoukrywacz - możliwość ukrycia dowolnego wpisu i komentarza

### ISSUE THREAD

**Issue by KonradZochowski** [wykopx/WykopX#5]

**Comment by wykopx** [comment]
Wersja testowa działającego Mirkoukrywacza. 

Zaktualizuj skrypt Wykop XS do wersji 2.6.8  
https://greasyfork.org/en/scripts/458860-wykop-xs  
Dodaj wersję testową Wykop X Canary:   
https://userstyles.world/style/8419/wykop-x-canary (i wyłącz normalną wersję, żeby nie działały obie)

**Comment by wykopx** [comment]
Zrobione.

Dodane w wersji 2.7.0
https://github.com/wykopx/WykopX/wiki/Extra#mirkoukrywacz
