### ISSUE TITLE
429 Too Many Requests You have sent too many requests in a given amount of time.

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#50]
Często pojawia mi się taki komunikat... w trybie incognito jest ok. Zastanawiam się, czy to wynika z wtyczki, która wysyła zbyt dużo zapytań do wykopu?... czy z czego? Ktoś tak ma również? Muszę odczekać jakąś dłuższą chwilę, aby wykop ponownie zaczął działać. Wyłączenie wtyczki nic nie daje (Wykop X i Wykop XS). A może to po prostu wina wykopu? Ktoś też tak ma?

**Comment by SPSPSP10000** [comment]
![111111111111111](https://user-images.githubusercontent.com/125213230/220847664-713f68f2-1877-41e7-b723-f2df37f2ffaf.png)

**Comment by wykopx** [comment]
Tak, inni wykopowicze również mają ten problem. Nie zależy to od Wykop X. 

https://wykop.pl/wpis/70474255/wykopchangelog-przepraszam-wykop-a-s-ze-to-napisze

![image](https://user-images.githubusercontent.com/123825950/220863779-50f2089f-f500-4583-b4e7-3c0fb5aa28a9.png)

**Comment by SPSPSP10000** [comment]
Nowy wypok ssie.
