### ISSUE TITLE
Rozjazd ikony komentarzy przy znalezisku z "wykop poleca"

### ISSUE THREAD

**Issue by houk001** [wykopx/WykopX#51]
![image](https://user-images.githubusercontent.com/18401686/220884824-51b80d7c-540a-493f-8678-42e1fdbbdee4.png)

**Comment by wykopx** [comment]
Naprawione w wersji  2.8.4

Dzięki za zgłoszenie :) sam bym tego nie zauważył bo sponsorowane mam ukryte
