### ISSUE TITLE
Środk. przycisk otwiera obrazek w nowej karcie

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#52]
Zauważyłem, że niezależnie czy jest to włączone, czy nie, to i tak środkowy przycisk otwiera obrazek w nowej karcie.
Przykładowy topic z obrazkiem:
https://wykop.pl/wpis/70502577/oranzeria-na-miare-moich-mozliwosci-skonczona-0-0-

PS. Po kliknięciu w obrazek "kółeczkiem" ustawia się "przesuwanie strony" myszką (nie wiem jak do końca to ująć) - dałoby radę to wyeliminować?

**Comment by wykopx** [comment]
Naprawione w wersji 2.8.5 + dodane nowe opcje wyboru przycisku myszy, który otwiera w nowej karcie.


![image](https://user-images.githubusercontent.com/123825950/220970746-28923744-1ddc-41e2-85d9-a39abf015af6.png)
