### ISSUE TITLE
Mirkoukrywacz - dublowanie numerów (błąd)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#54]
Takie coś mi się przed chwilą zrobiło.
![11111111111111](https://user-images.githubusercontent.com/125213230/221146011-5fd9bbb0-5e6f-40e3-840c-43af7e6c0616.png)

PS. Będzie czyszczenie tego po 24h? I czy można by dodać, dokładną datę ukrycia przez "nas" wpisu?

**Comment by wykopx** [comment]
Data ukrycia jest tutaj. 
Sekund dodawać nie ma sensu więc bardziej dokładnej nie będzie.

![edited_221146011-5fd9bbb0-5e6f-40e3-840c-43af7e6c0616.png](https://user-images.githubusercontent.com/123825950/221174327-a93a3eca-4bc7-46ed-a395-16c0ca22312e.png)

**Comment by SPSPSP10000** [comment]
A dałoby radę zrobić to chronologicznie?

**Comment by wykopx** [comment]
Lista ukrytych wpisów jest sortowana po numerze ID wpisu/komentarza, a numery ID są nadawane po kolei więc lista Mirkoukrywacza wyświetla wpisy w kolejności od najstarszych do najnowszych (data dodania wpisu/komentarza)

**Comment by SPSPSP10000** [comment]
Taka segregacja jest trochę niewygodna, bo jak coś ukryłem, to nie wiem, gdzie dokładnie to jest (szczególnie jeżeli mam dużo ukrytych)... a tak byłoby na końcu i odhaczam i elo :P
