### ISSUE TITLE
"Wykop Poleca"

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#55]
Nie wiem, czy opcja:
-Ukryj sponsorowa­ne znaleziska
jest z tym związana, ale jeżeli tak, to nie działa...

PS. Dałoby radę jakoś ukryć znaleziska typu "Wykop Poleca"?

**Comment by wykopx** [comment]
https://github.com/wykopx/WykopX/wiki/Changelog#291
# [2.9.1]   
Dodana Funkcja `⭐ Ukryj znaleziska "Wykop Poleca"`


![image](https://user-images.githubusercontent.com/123825950/221321498-961a03b6-dcc8-4f93-8e20-0e1e181796a8.png)

Dzięki za kolejne bardzo trafne zgłoszenie :)
