### ISSUE TITLE
➖➖ NOWE 2.8.6 ➖➖

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#57]
Nie ma niczego nowszego... pomimo że wersja jest 2.9.1.

**Comment by wykopx** [comment]
https://github.com/wykopx/WykopX/wiki/Changelog#291

**Comment by SPSPSP10000** [comment]
Chodzi mi o to, że nie ma "➖➖ NOWE 2.9.1 ➖➖ - pomimo takiej wersji... jest jedynie ➖➖ NOWE 2.8.6 ➖➖
![11111111111111](https://user-images.githubusercontent.com/125213230/221353258-e864b1a6-b71d-4977-b558-480f37a48f46.png)

**Comment by wykopx** [comment]
fixed, zaktualizuj

**Comment by SPSPSP10000** [comment]
Pisze, że nie ma żadnej nowej aktualizacji hmm...

**Comment by wykopx** [comment]
Pisze się "jest napisane"

**Comment by SPSPSP10000** [comment]
W wersji 2.9.2 już wszystko działa jak trzeba.
