### ISSUE TITLE
Mirkoukrywacz (powyżej 99 ukryć)

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#60]
Informuje, że coś ucina...
![22222](https://user-images.githubusercontent.com/125213230/221382642-2004cad1-d2af-4a3c-bcf6-824f953b3a41.png)

PS. Może warto byłoby wywalić całkowicie:
70512809 entry (całą tą tabelkę), nie jest zbyt potrzebna normalnemu zjadaczowi chleba.

Można by dać tak:
Numer, tytuł, data wpisu, data ukrycia.

**Comment by wykopx** [comment]
Fixed 2.9.4
