### ISSUE TITLE
Zmień rozmiar tekstu

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#61]
Który to niby tekst zmienia? U mnie się nic nie dzieje, niezależnie co wybiorę.

**Comment by wykopx** [comment]
Praktycznie każdy tekst i przycisk na wykopie zmienia wielkość fontu (ok. 95%)

![edited_Screenshot_20230226-094745.jpg](https://user-images.githubusercontent.com/123825950/221400939-92afc991-e443-4cc3-a3c7-eff766904c8c.jpg)

**Comment by SPSPSP10000** [comment]
Zaskoczyło u mnie, nie wiem, czemu początkowo nie działało, pomimo że wiele razy zmieniałem tą opcję (obstawiam, że po prostu czysto po aktualizacji wtyczki musiała się jeszcze nie wiem, jakoś przeładować, aby zaskoczyły zmiany), sorry za niepotrzebną wiadomość.
