### ISSUE TITLE
Wyjustowanie wpisów (komentarzy) użytkowników

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#62]
Fajnie jakby była taka opcja :)

**Comment by wykopx** [comment]
Moim zdaniem słabo to wygląda, ale spoko :)  

Może ktoś tak lubi. albo na telefonie może to lepiej działa :)

![image](https://user-images.githubusercontent.com/123825950/221405932-7768620e-bdb8-4a99-9af4-5462d8b9e611.png)

https://github.com/wykopx/WykopX/wiki/Changelog#293

**Comment by SPSPSP10000** [comment]
Dla mnie super :) Dzięki :)
