### ISSUE TITLE
Zmiana rozmiaru tytułu

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#63]
Może warto wprowadzić.

**Comment by SPSPSP10000** [comment]
Może warto byłoby wprowadzić coś takiego:
-Zmień rozmiar tekstu (obecnie jest i działa ok, ale również zmienia wielkość tytułu znaleziska, może warto byłoby to dać tylko i wyłącznie do tekstu typu: komentarz / wpis / opis znaleziska?)
+Zmień rozmiar tytułu

To taka luźna rozkminka.

**Comment by wykopx** [comment]
Duplikat https://github.com/wykopx/WykopX/issues/34
