### ISSUE TITLE
Pokazywanie notatki o użytkowniku pod paskiem ze schowanym komentarzem oraz podpisem "komentarz użytkownika z czarnej listy"

### ISSUE THREAD

**Issue by Ozjasz-Goldberg** [wykopx/WykopX#69]
Dzięki temu od razu można się zorientować czy czasami warto rozwinąć dany ukryty komentarz, bo koleś jest zablokowany robiąc spam czymkolwiek na mirko, ale może coś mądrego powie w znalezisku.

**Comment by wykopx** [comment]
Nie da się tego zrobić, bo w kodzie nie ma ani tego komentarza ani nawet nicku osoby, która jest tym użytkownikiem rzekomo zablokowanym.

Wykop nie daje żadnej informacji co jest pod zwiniętym komentarzem i wczytuje informacje dopiero po kliknięciu.

Niestety.
