### ISSUE TITLE
Umieszczenie ikonki ukrywania wpisów i komentarzy z mikroukrywacza obok nicka komentującego by oszczędzić miejsce w widoku mobilnym

### ISSUE THREAD

**Issue by Ozjasz-Goldberg** [wykopx/WykopX#70]
Ewentualnie można ustawić to w jednej linii z przyciskami odpowiedzi oraz ikony gwiazdki dodawania do ulubionych.

**Comment by wykopx** [comment]
Jeśli nick jest długi, to między nickiem i plusami nie ma w ogóle wolnego miejsca. Chciałem tam dość ten przycisk, ale niestety to niewykonalne na mobilce.

On teraz jest na jednej linii z przyciskami odpowiedzi i gwiazdki ulubionych i jak widzisz, rozjeżdża się.

Z tego samego powodu notatka do użytkownika jest poniżej avatara i nicku a nie obok. Bo nie ma tam miejsca

Duplikat
https://github.com/wykopx/WykopX/issues/14
