### ISSUE TITLE
Rozmiar nicków

### ISSUE THREAD

**Issue by SPSPSP10000** [wykopx/WykopX#71]
Przydałaby się opcja zmiany rozmiaru nicków - niekiedy mogą być za małe... szczególnie jakby się tekst dodatkowo powiększyło.
![2222222](https://user-images.githubusercontent.com/125213230/221626308-d5a116cd-c835-4b7d-871c-13a1cb759740.png)

**Comment by wykopx** [comment]
Rozmiar nazwy użytkownika naprawiony w wersji 2.10.3
