### ISSUE TITLE
Usunąć animacje i przeskoki

### ISSUE THREAD

**Issue by look997** [wykopx/WykopX#8]
Jedna z bardziej irytujących rzeczy do usunięcia: Animacje po kliknięciu w "POKAŻ KOMENTARZE", "Odpowiedz" oraz przeskok podczas pisania w polu tekstowym.

Moglibyście to usunąć za pomocą skryptu?
Czuję się przez to, jakby mnie ktoś chwycił za łeb, i zwracał go tam gdzie chce żebym patrzył, zamiast patrzeć sobie tam gdzie ja chcę. Okropne.

![POKAZ KOMENTARZE](https://user-images.githubusercontent.com/6620372/217870592-9a10591b-91ab-4542-8ccb-67ff696353eb.gif)
![odpowiedz](https://user-images.githubusercontent.com/6620372/217870606-3607f523-e6e4-4887-9fac-ec2eb4130167.gif)

chodzi żeby nie było wcale tej animacji ani przeskoku.

 to nawet w tej chwili nie mogłem odtworzyć. czasem tak jest że jak piszę to mi przesuwa scrolla, i jak kliknę pogrubienie, linka itd., to też potrafi przesuwać.

**Comment by lukaszpolowczyk** [comment]
Udało mi się przyłapać przeskok w polu tekstowym, tak to wygląda:
![przeskok w polu tekstowym](https://user-images.githubusercontent.com/16800535/217962224-1dcd4a09-d4d7-44d9-b8c4-3d8051086393.gif)

**Comment by look997** [comment]
Udało mi się przyłapać przeskok w polu tekstowym, tak to wygląda:
![przeskok w polu tekstowym](https://user-images.githubusercontent.com/6620372/217962433-2f97d793-76a1-49a2-81d0-60a7891632b9.gif)

**Comment by look997** [comment]
Kontynuacja: https://github.com/Wykop-pl/Issues/issues/102

**Comment by wykopx** [comment]
Możliwość wyłączenia wszystkich animacji  w wersji
Wykop X 2.11.16

https://github.com/wykopx/WykopX/wiki/Changelog#21116
