### ISSUE TITLE
✅ Tryb nocny - zmienione kolory na całkowicie czarne (Tryb dla ekranów AMOLED) 

### ISSUE THREAD

**Issue by wykopx** [wykopx/WykopX#89]
Funkcja `🌙 Super AMOLED Black 🔋` [[Pomysł 89](https://github.com/wykopx/WykopX/issues/89)]`     

Zamienia Tryb nocny na tryb Super Black dla ekranów AMOLED (oszczędzanie baterii przez całkowicie czarny kolor)   i bardzo ciemnych pomieszczeń.
Wykop zamiast szaro-brązowy jest teraz całkowicie czarny (kolory **rgb(0, 0, 0)**  czyli **#000000**)

![image](https://user-images.githubusercontent.com/123825950/222324955-773e7abe-9036-4758-addd-7f28a83b2e81.png)

**Comment by SPSPSP10000** [comment]
To powinno być chyba CLOSED :)

**Comment by wykopx** [comment]
Powinno :)
