### ISSUE TITLE
Przeniesienie Issues z repo `@felixd`

### ISSUE THREAD

**Issue by look997** [wykopx/WykopX#9]
Tutaj są, jest tam część moich rzeczy:
https://github.com/Wykop-pl/Issues/issues

Jak chcesz, to możesz poprzenosić tutaj te rzeczy, które jesteś w stanie zrobić.

I jeszcze źródła tego:

Rzeczy do naprawy:
https://wykop.pl/wpis/70077199/rzeczy-do-naprawy-w-nowywykop-w-sumie-wolniej-sie-
(nie zrobiłem z tego chyba żadnego issue na tamtym repo)

Co dodać na nowej bazie kodu:
https://wykop.pl/wpis/70077577/co-dodac-jak-juz-jest-nowa-baza-kodu-i-mozna-dodaw
(zrobiłem issue chyba z każdego)

**Comment by wykopx** [comment]
ok, przyjąłem.

Dzięki za linki.
