### ISSUE TITLE
Obserwowane Tagi - ułożone alfabetycznie

### ISSUE THREAD

**Issue by dracar1** [wykopx/WykopX#98]
Obserwowane tagi to coś co musi być na vikop, ale pewien mózg w nowej wersji to wyrzucił. Bardzo dobrze, że taka opcja się pojazwiła w WykopX. Aby przyjemniej się korzystało proponuję ułożenie alfabetyczne tagów :)

**Comment by wykopx** [comment]
Dodane w wersji 2.10.11

Funkcja `💻❎⭐ Sortuj "𝗧𝘄𝗼𝗷𝗲 𝗼𝗯𝘀𝗲𝗿𝘄𝗼𝘄𝗮𝗻­𝗲 𝘁𝗮𝗴𝗶" alfabetycz­nie`
![image](https://user-images.githubusercontent.com/123825950/223707890-2ba192df-2989-4a3e-9b57-39492caf5b23.png)

![image](https://user-images.githubusercontent.com/123825950/223708049-38b08264-75f6-4e8b-b3ab-9107ba8c98e1.png)
